const PERMISSION_OBJ = {
  DASHBOARD: {
    NAME: 'DASHBOARD',
    ACTIONS: ['VIEW', 'CREATE', 'UPDATE'],
  },
  PROPERTY: {
    NAME: 'PROPERTY',
    ACTIONS: ['VIEW', 'CREATE', 'UPDATE', 'DELETE'],
  },
  LEASING: {
    NAME: 'LEASING',
    ACTIONS: [
      'LIST_UNIT',
      'TENANT_MOVE_IN',
      'APPROVE_TENANT_MOVE_IN',
      'TENANT_MOVE_OUT',
      'APPROVE_TENANT_MOVE_OUT',
    ],
  },
  MAINTENANCE_REQUEST: {
    NAME: 'MAINTENANCE_REQUEST',
    ACTIONS: ['VIEW', 'CREATE', 'UPDATE', 'CLOSE_REQUEST'],
  },
  HOME_CLEANING_REQUEST: {
    NAME: 'HOME_CLEANING_REQUEST',
    ACTIONS: ['VIEW', 'CREATE', 'UPDATE', 'CLOSE_REQUEST'],
  },
  CAR_CLEANING_REQUEST: {
    NAME: 'CAR_CLEANING_REQUEST',
    ACTIONS: ['VIEW', 'CREATE', 'UPDATE', 'CLOSE_REQUEST'],
  },
  VISITOR_ACCESS_REQUEST: {
    NAME: 'VISITOR_ACCESS_REQUEST',
    ACTIONS: ['VIEW', 'CREATE', 'UPDATE', 'CLOSE_REQUEST', 'APPROVE_REQUEST'],
  },
  TRANSACTIONS: {
    NAME: 'TRANSACTIONS',
    ACTIONS: ['VIEW', 'CREATE', 'APPROVE_TRANSACTION'],
    PARENT: 'ACCOUNTING',
  },
  TRANSACTION_PAYMENTS: {
    NAME: 'TRANSACTION_PAYMENTS',
    ACTIONS: ['VIEW', 'CREATE', 'APPROVE_TRANSACTION'],
    PARENT: 'ACCOUNTING',
  },
  ADMIN: {
    NAME: 'ADMIN',
    ACTIONS: ['VIEW'],
    PARENT: 'CONTACTS',
  },
  MANAGER: {
    NAME: 'MANAGER',
    ACTIONS: ['VIEW', 'CREATE', 'UPDATE', 'DELETE'],
    PARENT: 'CONTACTS',
  },
  TENANT: {
    NAME: 'TENANT',
    ACTIONS: ['VIEW', 'CREATE', 'UPDATE', 'DELETE'],
    PARENT: 'CONTACTS',
  },
  SECURITY: {
    NAME: 'SECURITY',
    ACTIONS: ['VIEW', 'CREATE', 'UPDATE', 'DELETE'],
    PARENT: 'CONTACTS',
  },
  MAINTENANCE: {
    NAME: 'MAINTENANCE',
    ACTIONS: ['VIEW', 'CREATE', 'UPDATE', 'DELETE'],
    PARENT: 'CONTACTS',
  },
  CLEANING: {
    NAME: 'CLEANING',
    ACTIONS: ['VIEW', 'CREATE', 'UPDATE', 'DELETE'],
    PARENT: 'CONTACTS',
  },

  COMPLAINTS: {
    NAME: 'COMPLAINTS',
    ACTIONS: ['VIEW', 'CREATE', 'UPDATE', 'DELETE'],
  },
  VISITOR_SETTINGS: {
    NAME: 'VISITOR_SETTINGS',
    ACTIONS: ['UPDATE'],
  },
};

export default PERMISSION_OBJ;
