export const CONTACTS = 'CONTACTS';
export const TRANSACTION_CU_PROPERTIES = 'TRANSACTION_CU_PROPERIES';
export const TRANSACTION_CU_USERS = 'TRANSACTION_CU_USERS';
export const TRANSACTIONS = 'TRANSACTIONS';
